
  create or replace   view BALBOA_STAGING.L1_GOOGLE_ANALYTICS_4.engagement_events_report
  
    
    
(
  
    "EVENT_DATE" COMMENT $$The date on which the event occurred$$, 
  
    "PROPERTY" COMMENT $$The property associated with the event$$, 
  
    "FIVETRAN_ID" COMMENT $$The ID assigned by Fivetran to the event$$, 
  
    "EVENT_NAME" COMMENT $$The name of the event$$, 
  
    "TOTAL_USERS" COMMENT $$The total number of users involved in the event$$, 
  
    "EVENT_COUNT_PER_USER" COMMENT $$The number of times each user participated in the event$$, 
  
    "EVENT_COUNT" COMMENT $$The overall number of times the event occurred$$, 
  
    "TOTAL_REVENUE" COMMENT $$The total revenue generated by the event$$, 
  
    "FIVETRAN_SYNCED" COMMENT $$Flag indicating whether the event data has been synced from Fivetran$$
  
)

  copy grants as (
    with raw_source as (

    select *
    from RAW.GOOGLE_ANALYTICS_4.ENGAGEMENT_EVENTS_REPORT

),


final as (

    select
        "DATE"::date as event_date,
        "PROPERTY"::varchar as property,
        "_FIVETRAN_ID"::varchar as fivetran_id,
        "EVENT_NAME"::varchar as event_name,
        "TOTAL_USERS"::number as total_users,
        "EVENT_COUNT_PER_USER"::float as event_count_per_user,
        "EVENT_COUNT"::number as event_count,
        "TOTAL_REVENUE"::number as total_revenue,
        "_FIVETRAN_SYNCED"::timestamp_tz as fivetran_synced

    from raw_source

)

select * from final
  );

