# Generated by cartage 0.12.1 from pipelines/country_geo.yaml. Do not edit by hand:
# change the pipeline YAML, .cartage/config.yaml or templates/airflow/dag.py.j2, then run `cartage generate --target airflow`.
# The cartage project (including transforms/) must be deployed with this DAG; see PROJECT_DIR.
import os
import shlex

from airflow.decorators import dag, task
from orchestrate.utils import datacoves_utils

PROJECT_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), '../../../load/cartage'))


@dag(
    dag_id='country_geo',
    schedule=datacoves_utils.set_schedule('0 0 1 */12 *'),
    catchup=False,
    tags=['extract_and_load'],
    default_args=datacoves_utils.set_default_args(owner='Noel Gomez', owner_email='noel@example.com'),
)
def country_geo():
    @task.datacoves_bash(
        env={
            'UV_CACHE_DIR': '/tmp/uv_cache',
            'EXTRACT__NEXT_ITEM_MODE': 'fifo',
            'EXTRACT__MAX_PARALLEL_ITEMS': '1',
            'EXTRACT__WORKERS': '1',
            'NORMALIZE__WORKERS': '1',
            'LOAD__WORKERS': '1',
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__ACCOUNT': "{{ conn.get('main_load_keypair').extra_dejson['account'] or '' }}",
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__DATABASE': "{{ conn.get('main_load_keypair').extra_dejson['database'] or '' }}",
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__PRIVATE_KEY_CONTENT': "{{ conn.get('main_load_keypair').extra_dejson['private_key_content'] or '' }}",
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__ROLE': "{{ conn.get('main_load_keypair').extra_dejson['role'] or '' }}",
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__WAREHOUSE': "{{ conn.get('main_load_keypair').extra_dejson['warehouse'] or '' }}",
            'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__LOGIN': "{{ conn.get('main_load_keypair').login or '' }}",
        },
        append_env=True,
    )
    def cartage_run():
        command = [
            'uvx --from "cartage>=0.12.1" cartage',
            "--project-dir", shlex.quote(PROJECT_DIR),
            "run", 'pipelines/country_geo.yaml',
            "--env", "{{ var.value.get('cartage_env', 'airflow') }}",
        ]
        return " ".join(command)

    cartage_run()


country_geo()
