# Generated by cartage 0.5.0 from pipelines/us_population.yaml. Do not edit by hand:
# change the pipeline YAML, cartage.yaml or templates/airflow/dag.py.j2, then run `cartage generate --target airflow`.
# The cartage project (including transforms/) must be deployed with this DAG; see PROJECT_DIR.
import os
import shlex

import pendulum
from airflow import DAG
from operators.datacoves.bash import DatacovesBashOperator

from orchestrate.utils import datacoves_utils

PROJECT_DIR = os.path.normpath(os.path.join(os.path.dirname(__file__), '../../../load/cartage'))

default_args = datacoves_utils.set_default_args(owner="Noel Gomez", owner_email="noel@example.com")

with DAG(
    dag_id='us_population',
    schedule=datacoves_utils.set_schedule('0 0 1 */12 *'),
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    catchup=False,
    tags=['extract_and_load'],
    default_args=default_args,
) as dag:
    DatacovesBashOperator(
        task_id="cartage_run",
        bash_command='uvx --from "cartage[dlt]>=0.5.0" --with "dlt[snowflake,parquet]" --with pandas cartage' + " --project-dir " + shlex.quote(PROJECT_DIR) + " run " + "pipelines/us_population.yaml --env {{ var.value.get('cartage_env', 'prd') }}",
        env={'UV_CACHE_DIR': '/tmp/uv_cache', 'EXTRACT__NEXT_ITEM_MODE': 'fifo', 'EXTRACT__MAX_PARALLEL_ITEMS': '1', 'EXTRACT__WORKERS': '1', 'NORMALIZE__WORKERS': '1', 'LOAD__WORKERS': '1', 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__ACCOUNT': "{{ conn.get('main_load_keypair').extra_dejson['account'] or '' }}", 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__DATABASE': "{{ conn.get('main_load_keypair').extra_dejson['database'] or '' }}", 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__PRIVATE_KEY_CONTENT': "{{ conn.get('main_load_keypair').extra_dejson['private_key_content'] or '' }}", 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__ROLE': "{{ conn.get('main_load_keypair').extra_dejson['role'] or '' }}", 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__EXTRA__WAREHOUSE': "{{ conn.get('main_load_keypair').extra_dejson['warehouse'] or '' }}", 'CARTAGE_AIRFLOW__MAIN_LOAD_KEYPAIR__LOGIN': "{{ conn.get('main_load_keypair').login or '' }}"},
        append_env=True,
    )
