name: 'Run pytest with warning detection'
description: 'Runs pytest and reports warnings in the PR'

inputs:
  pytest_args:
    description: 'Arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run pytest
      shell: bash
      run: |
        # Run pytest and tee output to a file so we can process it
        pytest ${{ inputs.pytest_args }} 2>&1 | tee test_output.txt

        # Create GitHub warnings for any warning lines
        if grep -i "warning" test_output.txt; then
          grep -i "warning" test_output.txt | while read -r line; do
            echo "::warning::$line"
          done
        fi
