name: 'Run pytest with warning detection'
description: 'Runs pytest and reports warnings in the step summary and PR'

inputs:
  pytest_args:
    description: 'Arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run pytest
      shell: bash
      run: |
        # Capture output and still show it in logs
        OUTPUT=$(pytest ${{ inputs.pytest_args }} 2>&1)
        echo "$OUTPUT"

        # Create both step summary and GitHub annotations for warnings
        if echo "$OUTPUT" | grep -i "warning"; then
          # Add to step summary
          echo "## ⚠️ Test Warnings Detected" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUT" | grep -i "warning" -A 1 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

          # Create GitHub annotation
          echo "::warning::Test warnings detected"
          while IFS= read -r line; do
            if [[ $line == *"warning"* ]]; then
              echo "::warning::${line}"
            fi
          done <<< "$OUTPUT"

          # Make the check show neutral instead of success
          echo "warning=true" >> $GITHUB_OUTPUT
        fi
