name: 'Run pytest with warning detection'
description: 'Runs pytest and reports warnings in the PR'

inputs:
  pytest_args:
    description: 'Arguments to pass to pytest'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Run pytest
      uses: actions/github-script@v7
      env:
        PYTEST_ARGS: ${{ inputs.pytest_args }}
      with:
        script: |
          const { execSync } = require('child_process');
          try {
            const output = execSync(`pytest ${process.env.PYTEST_ARGS}`, { encoding: 'utf-8' });
            console.log(output);

            if (output.toLowerCase().includes('warning')) {
              // Create both a PR comment and a check run
              await github.rest.checks.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'Test Warnings',
                head_sha: context.sha,
                status: 'completed',
                conclusion: 'neutral',
                output: {
                  title: '⚠️ Test Warnings Detected',
                  summary: output.split('\n')
                    .filter(line => line.toLowerCase().includes('warning'))
                    .join('\n')
                }
              });

              // Also add a PR comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: '⚠️ **Test Warnings Detected:**\n```\n' +
                  output.split('\n')
                    .filter(line => line.toLowerCase().includes('warning'))
                    .join('\n') +
                  '\n```'
              });
            }
          } catch (error) {
            console.error(error);
            process.exit(error.status || 1);
          }
