default:
    target: test
    outputs:
      test:
        type: snowflake

        # More information for the options in this file
        # can be found here: https://docs.getdbt.com/dbt-cli/configure-your-profile

        threads: 8

        # Set the DATACOVES__MAIN__DATABASE in your CI
        database: "{{ env_var('DATACOVES__MAIN__DATABASE') }}"
        schema: NOT_DEFINED_FIX_ME

        # Set variable DATACOVES__MAIN__USER in your CI
        user: "{{ env_var('DATACOVES__MAIN__USER') }}"

        # Set variable DATACOVES__MAIN__PASSWORD in your CI
        password: "{{ env_var('DATACOVES__MAIN__PASSWORD') }}"

        # Additional Snowflake options
        # Find out more about Snowflake config options here:
        # https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile

        # Keypair authentication use instead of username and password
        # private_key_path: "{{ env_var('DBT_KEY_PATH') }}"
        # private_key_passphrase: "{{ env_var('DBT_KEY_PASSPHRASE') }}"

        # Set the DATACOVES__MAIN__ACCOUNT in your CI or update this to the actual Snowflake account like abc12345]
        account: "{{ env_var('DATACOVES__MAIN__ACCOUNT') }}"

        # Set the DATACOVES__MAIN__ROLE in your CI or update this to the actual role you use in Snowflake
        role: "{{ env_var('DATACOVES__MAIN__ROLE') }}"

        # Set the DATACOVES__MAIN__WAREHOUSE in your CI or update this to the actual Warehouse you use in Snowflake
        warehouse: "{{ env_var('DATACOVES__MAIN__WAREHOUSE') }}"

        client_session_keep_alive: False
        # query_tag: my_tag
