default:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: toa80779
            role: analyst
            user: "{{ snowflake_username }}"
            password: "{{ snowflake_password }}"
            database: balboa_dev
            warehouse: wh_transforming
            schema: "{{ snowflake_username }}"
            threads: 8
            keepalives_idle: 0
