
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'balboa'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model files
seeds:
  +schema: seeds
  +quote_columns: false
  +persist_docs:
      relation: true
      columns: true

snapshots:
  balboa:
    +target_database: raw
    +target_schema: snapshots

models:
  balboa:
    materialized: view
    +schema: z_schema_not_configured

    bays:
      bay_country:
        +schema: bay_country
      bay_covid:
        +schema: bay_covid
      bay_observability:
        +schema: bay_observability

    coves:
      cove_covid:
        +schema: cove_covid
      +materialized: table

    sources:
      account_usage:
        +schema: source_account_usage
      country_data:
        +schema: source_country_data
      starschema_covid19:
        +schema: source_starschema_covid19

    +persist_docs:
        relation: true
        columns: true

  post-hook:
    - "{{ dbt_snow_mask.apply_masking_policy() }}"

  # Snowflake Defualts
  +transient: "{{ 'false' if target.name == 'prod' else 'true' }}"
  copy_grants: true
  
  dbt_artifacts:
    +schema: source_dbt_artifacts
    staging:
      +schema: source_dbt_artifacts

tests:
  +store_failures: true

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'

  dbt_artifacts:
    dbt_artifacts_database: balboa # optional, default is your target database
    dbt_artifacts_schema: source_dbt_artifacts # optional, default is 'dbt_artifacts'
