# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'balboa'
# this is the project version, has nothing to do with dbt version
version: '1.0.0'
config-version: 2

require-dbt-version: ">=1.8.0"

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!

# Snowflake version
model-paths: ["models"]
snapshot-paths: ["snapshots"]

packages-install-path: dbt_packages

analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model files
seeds:
    +schema: SEEDS
    +docs:
        node_color: "#379965"
    +quote_columns: false
    +persist_docs:
        relation: true
        columns: true

snapshots:
    +enabled: "{{ True if target.database == 'balboa' else False }}"

    balboa:
        +target_database: raw
        +target_schema: SNAPSHOTS
    +docs:
        node_color: "#0f703d"

models:
    balboa:
        +materialized: view
        +schema: Z_SCHEMA_NOT_CONFIGURED

        L1_inlets:
            loans:
                +schema: L1_LOANS

        # L2_bays:
        #     +docs:
        #         node_color: "#000899"

        L3_coves:
            +docs:
                node_color: "#366ccf"
            loan_analytics:
                +schema: L3_LOAN_ANALYTICS
                # cannot persist docs on dynamic tables
                +persist_docs:
                    relation: false
            +materialized: table

        +persist_docs:
            relation: true
            columns: true

    # Snowflake Defaults
    +transient: "{{ 'false' if target.name == 'prd' else 'true' }}"
    copy_grants: true

# This creates a view in snowflake that will track failures. Usefull for dynamic tables dbt isnt refreshing
# Run dbt with:  --vars '{"persist_tests": "true", "tests_model": "test_failures"}'
on-run-end:
  - "{{ create_test_failure_view(results) }}"

# In development, this will be created in your user schema
data_tests:
    +store_failures: true
    +schema: DBT_TEST__AUDIT
    +store_failures_as: view

vars:
    'dbt_date:time_zone': 'America/Los_Angeles'
