name: 🪾 Branch Validation

on:
  pull_request:
    branches: [ '*' ]

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    name: Validate Branch Names and Merge Rules and assure branch has changes from main

    env:
      SOURCE_BRANCH: github.head_ref
      TARGET_BRANCH: github.base_ref

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate current branch
      run: automate/git/branch_validator.py
