name: pre-commit

on:
  push:
    branches:
      - dev_bruno

jobs:
  dbt-checkpoint:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DATACOVES__MAIN__PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - id: install_dbt
        run: pip install dbt-core==1.6.3
        shell: bash

      - name: Run dbt checkpoint
        uses: pre-commit/action@v3.0.1
