name: test s3 upload

on:  # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:

jobs:
  upload_file:
    name: Upload_s3_file
    runs-on: ubuntu-latest
    container: datacoves/ci-basic-dbt-snowflake:3.2

    defaults:
      run:
        working-directory: /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/transform

    env:
      DBT_ARTIFACTS_BUCKET: "convexa-local"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set Secure Directory
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # - name: Upload artifacts to S3
      #   run: |
      #     # Create an array of files to check and upload
      #     # files=("target/sources.json" "target/manifest.json" "target/catalog.json" "target/run_results.json")
      #     files=("dbt_project.yml" ".sqlfluff" "target/catalog.json" "target/run_results.json")

      #     # Loop through each file and upload if it exists
      #     for file in "${files[@]}"; do
      #       if [ -f "$file" ]; then
      #         echo "Uploading $file to S3..."
      #         aws s3 cp "$file" "s3://${DBT_ARTIFACTS_BUCKET}/dbt_artifacts/$(basename $file)"
      #       else
      #         echo "File $file does not exist, skipping..."
      #       fi
      #     done

      - name: Upload artifacts to S3
        run: |
          # Check and upload each file individually
          for file in .sqlfluff dbt_project.yml target/sources.json target/manifest.json target/catalog.json target/run_results.json; do
            if [ -f "$file" ]; then
              echo "Uploading $file to S3..."
              aws s3 cp "$file" "s3://${DBT_ARTIFACTS_BUCKET}/dbt_artifacts/$(basename $file)"
            else
              echo "File $file does not exist, skipping..."
            fi
          done
